# -*- coding: utf-8 -*-
"""POO-2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZAOs5gPOTwrAmdsZetE6HdLDn0F4nKM
"""



"""#EX01
 Converter F para C OBS: Entrada: F processamento: C = (5/9)(F-32) Saída: C
"""

F = float(input("Digite valor em Graus Farenheit: "))
C = (5/9)*(F-32)
print("Graus Celsius: ", C)

"""Resolução do mesmo exercício usando a função (método) printf"""

F = float(input("Digite valor em Graus Farenheit: "))
C = (5/9)*(F-32)
print(f"O Valor de {F}°Farenheit corresponde ao valor de {C}°C ")

"""#EX02
Código de um programa que solicite ao usuário digitar medida em polegadas e converter o valor dado
para milímetros. (1”=25,4mm)

Entrada : P
Processamento: MM = P*25.4
Saída: MM
"""

P = float(input("Digite valor em Polegadas: "))
MM = P*25.4
print(f"O valor de {P}pol corresponde ao valor de {MM:.2f}mm")

"""código de um programa que solicite ao usuário digitar uma medida
em milímetros, elaborar um programa para converter o valor dado para polegadas.
"""

M = float(input("Digite valor em Milimetros: "))
P = M/25.4
print(f"O valor de {MM} Milimetros corresponde ao valor de {P:.2f} Polegadas")

"""#PROGRAMA VERIFICAR DE IDADE PARA VOTAÇÃO"""

#entrada: Idade
#Saída: "Pode Votar ou Não"

idade = int(input("Digite sua idade: "))
if idade >= 16:
  print("Pode Votar")
else :
  print("Não pode votar")